[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "graduation_project"
version = "0.0.1"
description = "A short description of the project."
authors = [
  { name = "Tan Dat" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = ">=3.10"


[tool.ruff]
line-length = 99
src = ["du_an_tot_nghiep"]
include = ["pyproject.toml", "du_an_tot_nghiep/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["du_an_tot_nghiep"]
force-sort-within-sections = true

